### ISSUE TITLE
reproduce the resampling

### ISSUE THREAD

**Issue by YunruiZhang** [time-series-machine-learning/tsml-eval#79]
Hi, I am trying to reproduce the resampling result in the paper "The great multivariate time series classification bake off: a review and experimental evaluation of recent algorithmic advances". However, I did not find the code that generates the resampled datasets.  In `tsml-eval/tsml_eval/experiments/experiments.py`  function ` _load_data`, I could see that the resamples are loaded as files. Can someone share the code for resampling the dataset? 

Thanks.

**Comment by MatthewMiddlehurst** [comment]
Hi, I believe this paper used our old Java package to run most of the results, and used the resampling from that where possible. Think that is correct @TonyBagnall?

This would be the function https://github.com/time-series-machine-learning/tsml-java/blob/master/src/main/java/experiments/data/DatasetLoading.java#L298.

Our papers using this package will use https://github.com/time-series-machine-learning/tsml-eval/blob/main/tsml_eval/utils/experiments.py#L94 for classification.

Unfortunately due to different rng you are unlikely to be able to reproduce the resamples in Python.
